export const GET_POKEMON_DATA = 'GET_POKEMON_DATA'
export const FILTER_POKEMONS = 'FILTER_POKEMONS'
export const ADD_TYPE_POKEMON = 'ADD_TYPE_POKEMON'
export const REMOVE_TYPE_POKEMON = 'REMOVE_TYPE_POKEMON'
export const CHANGE_OFFSET = 'CHANGE_OFFSET'

export const START_LOADING = 'START_LOADING'
export const ERROR_LOADING = 'ERROR_LOADING'
export const END_LOADING = 'END_LOADING'
